# Generated by Django 4.2.3 on 2023-10-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='base/static/base/images'),
        ),
    ]
